# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=20, max_digits=30)),
                ('y', models.DecimalField(decimal_places=20, max_digits=30)),
                ('z', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gyro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=20, max_digits=30)),
                ('y', models.DecimalField(decimal_places=20, max_digits=30)),
                ('z', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
    ]
