# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_accel_gyro'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Accel'),
        ),
        migrations.AddField(
            model_name='user',
            name='gyro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Gyro'),
        ),
    ]
